---
- name: Apply common configuration to all hosts
  hosts: all
  roles:
    - common
    - docker
    - ros
    - docker_compose
    - nfs_client

- name: Apply desktop configuration
  hosts: workstations
  roles:
    - desktop
