---
- name: Add Google Chrome GPG key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google-chrome.asc
    mode: "0644"

- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc]
      https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
    update_cache: true
