---
- name: Add VS Code GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: "0644"

- name: Add VS Code repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc]
      https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Install VS Code
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
