---
- name: Check if ROS 2 is supported on this OS
  ansible.builtin.set_fact:
    ros_distro: "{{ ros_distro_map[ansible_distribution_release] | default('') }}"

- name: Skip if ROS 2 is not supported on this OS release
  ansible.builtin.debug:
    msg: >-
      ROS 2 is not supported on {{ ansible_distribution }} {{ ansible_distribution_release }}.
      Supported releases: {{ ros_distro_map.keys() | join(', ') }}
  when: ros_distro == ''

- name: Install ROS 2
  ansible.builtin.include_tasks: install.yml
  when: ros_distro != ''
