---
- name: Fail if docker_compose_user is not set
  ansible.builtin.fail:
    msg: "docker_compose_user must be set to deploy compose services"
  when: docker_compose_user == ""

- name: Get uid for {{ docker_compose_user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ docker_compose_user }}"

- name: Set uid fact
  ansible.builtin.set_fact:
    docker_compose_uid: "{{ ansible_facts.getent_passwd[docker_compose_user][1] }}"

- name: Deploy compose services
  ansible.builtin.include_tasks: service.yml
  loop: "{{ docker_compose_services }}"
  loop_control:
    loop_var: service_name
